apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
  AWS_BUCKET: <base64 aws unique bucket name>
  AWS_PROFILE: <base64 aws profile name in cridentials like default>
  AWS_REGION: <base64 aws region like eu-central-1>
  JWT_SECRET: <base64 jwt secret like hello>