apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  labels:
    app: feed-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
      - name: feed-service
        image: selimdockerhub/feed-service
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"    
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: feed-service-secret
              key: POSTGRES_HOST
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: feed-service-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feed-service-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: feed-service-secret
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: JWT_SECRET               
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: AWS_REGION    
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: AWS_PROFILE  
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret    
